config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'registrations'}
  # Nice job customizing user sign-up
  root "pages#index"
  get "/pages/:page" => "pages#show"
  # To use a different named parameter than :id, you can also use the 'param' option:
  # resources :pages, param: :page, only: [:show]


  resources :restaurants
  resources :bowls do
    resources :comments
    resources :topping_tags, only: [:new, :create]
  end
  resources :bowls, only: [:index, :show] do
   member do
     post 'add_favorite'
     delete 'remove_favorite'
   end
 end
 resources :toppings
end

app/models/bowl.rb
class Bowl < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :restaurant
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :topping_tags, dependent: :destroy
  has_many :toppings, through: :topping_tags
end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
  one option in rails controllers to dry up your code is to abstract finding the
  instance of a bowl into a method. Example:
  before_action :find_bowl

  # GET /bowls
  def index
    @bowls = Bowl.all
  end

  # GET /bowls/new
  def new
    @bowl = Bowl.new
  end

  # POST /bowls
  def create
    @bowl = current_user.bowls.new(bowl_params)
    if @bowl.save
      flash[:notice] = "#{@bowl.title} created successfully."
      redirect_to bowl_path(@bowl)
    else
      flash[:alert] = "Something went wrong trying to save your bowl!"
      render :new
    end
  end

  # GET /bowls/1
  def show
    @bowl = Bowl.find(params[:id])
    @restaurant = @bowl.restaurant
    @comments = @bowl.comments
    @topping_tag = ToppingTag.new
  end

  # GET /bowls/1/edit
  def edit
    @bowl = Bowl.find(params[:id])
    if @bowl.user != current_user
      flash[:alert] = "Only the author of a bowl can edit!"
      redirect_to bowl_path(@bowl)
    end
  end

  # PATCH/PUT /bowls/1
  def update
    @bowl = Bowl.find(params[:id])
    if @bowl.user == current_user
      @bowl.update(bowl_params)
      flash[:notice] = "Bowl updated successfully."
    else
      flash[:alert] = "Only the author of a bowl can edit!"
    end
    redirect_to bowl_path(@bowl)
  end

  # DELETE /bowls/1
  def destroy
    @bowl = Bowl.find(params[:id])
    if @bowl.user == current_user
      @bowl.destroy
      flash[:alert] = "Bowl deleted!"
    else
      flash[:alert] = "Only the author of a bowl can delete it!"
    end
    redirect_to bowls_path
  end

  def add_favorite
    @bowl = Bowl.find(params[:id])
    @bowl.favorites.create(user: current_user)
    redirect_to bowl_path(@bowl)
  end

  def remove_favorite
    @bowl = Bowl.find(params[:id])
    Favorite.find_by(user: current_user, bowl_id: params[:id]).destroy
    redirect_to bowl_path(@bowl)
  end

  private

    def find_bowl
      if params[:id]
        @bowl = Bowl.find(params[:id])
      end
    end

    # Prevent evil people from messing with my params
    def bowl_params
      params.require(:bowl).permit(:price, :broth, :noodle, :protein, :is_veg, :title, :review, :img_url, :restaurant_id)
    end
end

app/helpers/bowls_helper.rb
module BowlsHelper
end

app/views/bowls/_form.html.erb
<div class="form">
  <%= form_for @bowl do |f| %>
  <strong>Thanks for adding to our collection! First up, how would you describe this bowl?</strong> <br><br>
  We've seen titles like "Best Bowl I've Ever Binged On" and "Savory, Salty, Seaweedy!" Don't be afraid to get creative.<br><br>
  <div class="formitem">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br>
  Nice. Where'd you eat this delicious bowl of ramen?<br><br>
  <div class="formitem">
    <%= f.label :restaurant %>
    <%= select(:bowl, :restaurant_id, Restaurant.all.collect{|rest| [rest.name, rest.id]}.sort) %><br><br>
    Not seeing your restaurant? Click <%= link_to 'here', new_restaurant_path %> to add it to our database first!<br><br>
  </div>
  Now for some optional details...<br><br>
    <div class="formitem">
      <%= f.label :"price (in USD)" %><br>
      <%= f.text_field :price %>
    </div>
    <div class="formitem">
      <%= f.label :broth %><br>
      <%= f.text_field :broth %>
    </div>
    <div class="formitem">
      <%= f.label :noodle %><br>
      <%= f.text_field :noodle %>
    </div>
    <div class="formitem">
      <%= f.label :protein %><br>
      <%= f.text_field :protein %>
    </div>
    <div class="formitem">
      <%= f.label :"Vegetarian? (True or False)" %><br>
      <%= f.text_field :is_veg %>
    </div>
    <div class="formitem">
      <%= f.label :image_URL %> <br>
      <%= f.text_field :img_url %>
    </div>
    <br><br>
    Any additional comments?<br><br>
    <div class="formitem">
      <%= f.label :review %><br>
      <%= f.text_area :review, class: "reviewinput"%>
    </div>
    <div class="formbutton">
      <%= f.submit %>
    </div>
  <% end %>

app/views/bowls/edit.html.erb
<h1>Editing Bowl Info</h1>

<div class="main-content-form">
  <%= render 'form', bowl: @bowl %>

  <%= form_for @bowl, method: :delete do |f| %>
    <%= f.submit "Delete!", class: "delete" %>
  <% end %>

</div>
<%= link_to 'Back', bowl_path %>

app/views/bowls/index.html.erb
<h1>Browse Our Bowls</h1>

<div class="main-content-box">
  <div class = "primary-list">
    <% @bowls.each do |bowl| %>
    <div class="list-item">
      <div class="thumbnail-frame">
          <%=image_tag bowl.img_url, class: "thumbnail-image"%>
        </div>
        <div class="thumbnail-link">
          <%= link_to bowl.title, bowl %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bowls/new.html.erb
<h1>Add a New Bowl</h1>

<div class="main-content-form">
  <%= render 'form', bowl: @bowl %>
</div>

app/views/bowls/show.html.erb
<div class="main-header">
    <div class="main-info">
      <h2><%= @bowl.title %></h2>
        Posted: <%= @bowl.created_at.strftime("%m-%d-%Y") %><br>
        By: <%= @bowl.user.first_name.capitalize %> in <%= @bowl.user.city %><br>
    </div>
    <div class="main-options">
      <% if @bowl.user == current_user %>
        <%= link_to 'Edit Post', edit_bowl_path(@bowl) %>
      <% end %><br><br>
      <% if @bowl.users.include? current_user %>
        <%= link_to "&hearts;".html_safe, remove_favorite_bowl_path(@bowl), method: :delete, class: "fav" %>
      <% else %>
        <%= link_to "&hearts;".html_safe, add_favorite_bowl_path(@bowl), method: :post, class: "no-fav" %>
      <% end %><br>
    </div>
</div>

<div class="main-content-box">

  <div class="main-image-box">
    <%= image_tag @bowl.img_url, class: "main-image" %>
  </div>

  <div class="main-content">
      <h4>Bowl Info:</h4>
      <ul>
        <li>Price: $<%= @bowl.price %></li>
        <li>Broth: <%= @bowl.broth %></li>
        <li>Noodle: <%= @bowl.noodle %></li>
        <li>Protein: <%= @bowl.protein %></li>
        <li>Vegetarian? <%= @bowl.is_veg %></li>
      </ul>

    <h4>Toppings:</h4>
    <ul>
      <% if @bowl.topping_tags %>
          <% @bowl.topping_tags.each do |topping_tag| %>
             <li><%= link_to topping_tag.topping.name, topping_path(topping_tag.topping) %></li>
          <% end %>
      <% end %>
    </ul>
    <div class="main-content-form">
      <% if @bowl.user == current_user %>
        <%= form_for [@bowl, @topping_tag] do |f| %>
          <%= f.text_field :topping %>
          <%= f.submit "Add topping" %>
        <% end %>
      <% end %>
    </div>
    <h4>Review:</h4>
      <%= @bowl.review %><br>
    <h4>Eaten at:</h4>
      <strong><%= link_to @restaurant.name, restaurant_path(@restaurant) %><br></strong>
      <%= @restaurant.address %><br>
      <%= @restaurant.city %>, <%= @restaurant.state %>,<%= @restaurant.zip %><br>
    <br>
  </div>
</div>
<div class="comment-box">
  <h3>Comments <%= link_to "+  ", new_bowl_comment_path(@bowl) %></h3>
  <% if @comments %>
    <% @comments.each do |c| %>
      <div class="comment">
          <div class="comment-image-box">
            <%= image_tag c.user.img_url, class: "comment-image" %>
          </div>
          <div class="comment-content-box">
            <strong><%= c.name %><br></strong>
            <%= c.created_at.strftime("%m-%d-%Y") %><br>
            <%= c.comment %><br>
            <% if c.user == current_user %>
              <%= link_to "(edit)", edit_bowl_comment_path(c.bowl_id, c) %>
              <% end %>
          </div>
      </div>
    <% end %>
  <% end %>
</div>