config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'registrations'}
  # Nice job customizing user sign-up
  root "pages#index"
  get "/pages/:page" => "pages#show"
  # To use a different named parameter than :id, you can also use the 'param' option:
  # resources :pages, param: :page, only: [:show]


  resources :restaurants
  resources :bowls do
    resources :comments
    resources :topping_tags, only: [:new, :create]
  end
  resources :bowls, only: [:index, :show] do
   member do
     post 'add_favorite'
     delete 'remove_favorite'
   end
 end
 resources :toppings
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :bowls
  # should you have dependent destroy above?
  validates :name, uniqueness: true

  # nice job using validations
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  # GET /restaurants
  def index
    @restaurants = Restaurant.all.sort
    @restaurants.sort! { |a,b| a.name.downcase <=> b.name.downcase }
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "#{@restaurant.name} created successfully."
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = "Something went wrong trying to save your restaurant."
      render :new
    end
  end

  # GET /restaurants/1
  def show
    @restaurant = Restaurant.find(params[:id])
    @bowls = @restaurant.bowls
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # PATCH/PUT /restaurants/1
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    flash[:notice] = "Restaurant updated successfully."
    redirect_to restaurant_path(@restaurant)
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:alert] = "Restaurant deleted!"
    redirect_to restaurants_path
  end

  private
    # Prevent evil people from messing with my params
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city, :zip, :img_url)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="form">
  <%= form_for @restaurant do |f| %>
    <div class="formitem">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="formitem">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="formitem">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="formitem">
      <%= f.label :state %><br>
      <%= f.text_field :state %>
    </div>
    <div class="formitem">
      <%= f.label :zip %><br>
      <%= f.text_field :zip %>
    </div>
    <div class="formitem">
      <%= f.label :"image URL" %><br>
      <%= f.text_field :img_url %>
    </div>
    <div class="formitem">
      <%= f.label :"pricepoint ($, $$, $$$, $$$$)" %><br>
      <%= f.text_field :price %>
    </div>
    <div class="formbutton">
      <%= f.submit %>
    </div>
  <% end %>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<div class="main-content-form">
  <%= render 'form', restaurant: @restaurant %>


<%= form_for @restaurant, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div class="main-content-box">
  <div class = "primary-list">
      <% @restaurants.each do |restaurant| %>
      <div class="list-item">
        <div class="thumbnail-frame">
          <%=image_tag restaurant.img_url, class: "thumbnail-image"%>
        </div>
         <%= link_to restaurant.name, restaurant %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<div class="main-content-form">
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>
<div class="main-content-box">
  <p>Created: <%= @restaurant.created_at.strftime("%m-%d-%Y") %> | <%= link_to 'Edit', edit_restaurant_path(@restaurant) %></p>
  <%= image_tag @restaurant.img_url, class: "restimage" %>
  <br><br>
      <h4>Restaurant Info:</h4>
      <%= @restaurant.address %><br>
      <%= @restaurant.city %>, <%= @restaurant.state %>,<%= @restaurant.zip %><br>
      <%= @restaurant.price %>
  <br><br>
  <h4>Bowls</h4>
  <%= link_to 'Add a Bowl', new_bowl_path %>
  <ul>
    <% @restaurant.bowls.each do |b| %>
      <li><%= link_to b.title, bowl_path(b) %></li>
    <% end %>
  </ul>
</div>