config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'registrations'}
  # Nice job customizing user sign-up
  root "pages#index"
  get "/pages/:page" => "pages#show"
  # To use a different named parameter than :id, you can also use the 'param' option:
  # resources :pages, param: :page, only: [:show]


  resources :restaurants
  resources :bowls do
    resources :comments
    resources :topping_tags, only: [:new, :create]
  end
  resources :bowls, only: [:index, :show] do
   member do
     post 'add_favorite'
     delete 'remove_favorite'
   end
 end
 resources :toppings
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramen Shaman</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <div class="nav-logo-box">
        <%= image_tag "rs_logo.png", class: "logo"%>
        <%= link_to 'RAMEN SHAMAN', root_path %>
      </div>
      <div class="nav-links-box">
        <% if current_user %>
          <div class="logged-in">
            <p>Logged in as: <%= current_user.first_name %> <%= current_user.last_name %></p>
            <%= link_to 'My Profile', "/pages/myprofile" %> |
            <%= link_to 'Edit Profile', edit_user_registration_path %> |
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>

          </div>
        <% end %>
      </div>
    </nav>

    <div class="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="yield-content">
        <%= yield %>
      </div>
    </div>
      <% unless current_page?(root_path) %>
      <div class="navbar">
        <ul>
            <li><%= link_to 'View Bowls', bowls_path %></li>
            <li><%= link_to 'Add Bowl', new_bowl_path %></li>
          <li><%= link_to 'View Restaurants', restaurants_path %></li>
          <li><%= link_to 'Add Restaurant', new_restaurant_path %></li>
          <% if current_user %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </ul>
      </div>
      <% end %>
    <div class = "footer">
      <p>© <%= Date.today.year %> Made with &hearts; by Liz Jewell</p>
    </div>
  </body>
</html>